### ISSUE TITLE
doesnt work since 1.0 same errors on 1.2 and 1.1 versions

### ISSUE THREAD

**Issue by NFT2626** [CreativerseMC/CreativerseMC-Plugin#4] opened 2022-03-04 13:50 UTC
[08:46:22 WARN]: java.lang.IllegalArgumentException: count < 1
[08:46:22 WARN]: 	at Creativerse.jar//de.javagl.jgltf.impl.v2.Accessor.setCount(Accessor.java:246)
[08:46:22 WARN]: 	at Creativerse.jar//de.javagl.jgltf.model.impl.creation.BufferStructureGltfV2.createAccessor(BufferStructureGltfV2.java:89)
[08:46:22 WARN]: 	at Creativerse.jar//de.javagl.jgltf.model.impl.creation.BufferStructureGltfV2.createAccessors(BufferStructureGltfV2.java:67)
[08:46:22 WARN]: 	at Creativerse.jar//io.github.oguzhancevik.obj2gltf.creator.ObjGltfAssetCreatorV2.convert(ObjGltfAssetCreatorV2.java:277)
[08:46:22 WARN]: 	at Creativerse.jar//io.github.oguzhancevik.obj2gltf.creator.ObjGltfAssetCreatorV2.create(ObjGltfAssetCreatorV2.java:202)
[08:46:22 WARN]: 	at Creativerse.jar//io.github.oguzhancevik.obj2gltf.ConvertObjToGltf.convert(ConvertObjToGltf.java:103)
[08:46:22 WARN]: 	at Creativerse.jar//com.creativerse.renderer.McTo3D.convertObjToGltf(McTo3D.java:49)
[08:46:22 WARN]: 	at Creativerse.jar//com.creativerse.commands.Save.lambda$onCommand$0(Save.java:100)
[08:46:22 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:46:25 WARN]: java.io.FileNotFoundException: plugins/Creativerse/../../cache/1646401581927.gltf (No such file or directory)
[08:46:25 WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[08:46:25 WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[08:46:25 WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[08:46:25 WARN]: 	at Creativerse.jar//com.creativerse.requests.Request.upload(Request.java:20)
[08:46:25 WARN]: 	at Creativerse.jar//com.creativerse.Nft.createJSON(Nft.java:24)
[08:46:25 WARN]: 	at Creativerse.jar//com.creativerse.commands.Save.lambda$onCommand$0(Save.java:107)
[08:46:25 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by CreativerseMC** [comment] 2022-03-06 23:32
Duplicate of #2, closing

**Closed as completed by CreativerseMC** 2022-03-06 23:32 UTC
